import styles from "../styles/Home.module.css";
import React from "react";
import Countdown from "react-countdown";

export default function Home() {
  return (
    <div className={styles.container}>
      <title>⚡️ Whooptopia 2022 ⚡️</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <main className={styles.main}>
        <h1 className={styles.title}>⚡ Whooptopia 2022 ⚡️</h1>
        <h2 lassName={styles.title}> January 15th-17th 2022 </h2>
        <h3>
          <Countdown date={1642204800000}></Countdown>
        </h3>
      </main>
    </div>
  );
}
